/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { LotteryContract } from './Lottery'

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: 'Lottery'): LotteryContract
    }
  }
}

export { LotteryContract, LotteryInstance } from './Lottery'
